type AlphabetEntry = {rom: string; hira: string; kata: string}

export const alphabet: {[section: string]: AlphabetEntry[]} = {
	basics: [
		{rom: 'a', hira: 'あ', kata: 'ア'},
		{rom: 'i', hira: 'い', kata: 'イ'},
		{rom: 'u', hira: 'う', kata: 'ウ'},
		{rom: 'e', hira: 'え', kata: 'エ'},
		{rom: 'o', hira: 'お', kata: 'オ'},
		{rom: 'ka', hira: 'か', kata: 'カ'},
		{rom: 'ki', hira: 'き', kata: 'キ'},
		{rom: 'ku', hira: 'く', kata: 'ク'},
		{rom: 'ke', hira: 'け', kata: 'ケ'},
		{rom: 'ko', hira: 'こ', kata: 'コ'},
		{rom: 'sa', hira: 'さ', kata: 'サ'},
		{rom: 'shi', hira: 'し', kata: 'シ'},
		{rom: 'su', hira: 'す', kata: 'ス'},
		{rom: 'se', hira: 'せ', kata: 'セ'},
		{rom: 'so', hira: 'そ', kata: 'ソ'},
		{rom: 'ta', hira: 'た', kata: 'タ'},
		{rom: 'chi', hira: 'ち', kata: 'チ'},
		{rom: 'tsu', hira: 'つ', kata: 'ツ'},
		{rom: 'te', hira: 'て', kata: 'テ'},
		{rom: 'to', hira: 'と', kata: 'ト'},
		{rom: 'na', hira: 'な', kata: 'ナ'},
		{rom: 'ni', hira: 'に', kata: 'ニ'},
		{rom: 'nu', hira: 'ぬ', kata: 'ヌ'},
		{rom: 'ne', hira: 'ね', kata: 'ネ'},
		{rom: 'no', hira: 'の', kata: 'ノ'},
		{rom: 'ha', hira: 'は', kata: 'ハ'},
		{rom: 'hi', hira: 'ひ', kata: 'ヒ'},
		{rom: 'fu', hira: 'ふ', kata: 'フ'},
		{rom: 'he', hira: 'へ', kata: 'ヘ'},
		{rom: 'ho', hira: 'ほ', kata: 'ホ'},
		{rom: 'ma', hira: 'ま', kata: 'マ'},
		{rom: 'mi', hira: 'み', kata: 'ミ'},
		{rom: 'mu', hira: 'む', kata: 'ム'},
		{rom: 'me', hira: 'め', kata: 'メ'},
		{rom: 'mo', hira: 'も', kata: 'モ'},
		{rom: 'ya', hira: 'や', kata: 'ヤ'},
		{rom: 'yu', hira: 'ゆ', kata: 'ユ'},
		{rom: 'yo', hira: 'よ', kata: 'ヨ'},
		{rom: 'ra', hira: 'ら', kata: 'ラ'},
		{rom: 'ri', hira: 'り', kata: 'リ'},
		{rom: 'ru', hira: 'る', kata: 'ル'},
		{rom: 're', hira: 'れ', kata: 'レ'},
		{rom: 'ro', hira: 'ろ', kata: 'ロ'},
		{rom: 'wa', hira: 'わ', kata: 'ワ'},
		{rom: 'wo', hira: 'を', kata: 'ヲ'},
		{rom: 'n', hira: 'ん', kata: 'ン'},
	],
	dakutenHandakuten: [
		{rom: 'ga', hira: 'が', kata: 'ガ'},
		{rom: 'gi', hira: 'ぎ', kata: 'ギ'},
		{rom: 'gu', hira: 'ぐ', kata: 'グ'},
		{rom: 'ge', hira: 'げ', kata: 'ゲ'},
		{rom: 'go', hira: 'ご', kata: 'ゴ'},
		{rom: 'za', hira: 'ざ', kata: 'ザ'},
		{rom: 'ji', hira: 'じ', kata: 'ジ'},
		{rom: 'zu', hira: 'ず', kata: 'ズ'},
		{rom: 'ze', hira: 'ぜ', kata: 'ゼ'},
		{rom: 'zo', hira: 'ぞ', kata: 'ゾ'},
		{rom: 'da', hira: 'だ', kata: 'ダ'},
		{rom: 'ji', hira: 'ぢ', kata: 'ヂ'},
		{rom: 'zu', hira: 'づ', kata: 'ヅ'},
		{rom: 'de', hira: 'で', kata: 'デ'},
		{rom: 'do', hira: 'ど', kata: 'ド'},
		{rom: 'ba', hira: 'ば', kata: 'バ'},
		{rom: 'bi', hira: 'び', kata: 'ビ'},
		{rom: 'bu', hira: 'ぶ', kata: 'ブ'},
		{rom: 'be', hira: 'べ', kata: 'ベ'},
		{rom: 'bo', hira: 'ぼ', kata: 'ボ'},
		{rom: 'pa', hira: 'ぱ', kata: 'パ'},
		{rom: 'pi', hira: 'ぴ', kata: 'ピ'},
		{rom: 'pu', hira: 'ぷ', kata: 'プ'},
		{rom: 'pe', hira: 'ぺ', kata: 'ペ'},
		{rom: 'po', hira: 'ぽ', kata: 'ポ'},
	],
	youon: [
		{rom: 'kya', hira: 'きゃ', kata: 'キャ'},
		{rom: 'kyu', hira: 'きゅ', kata: 'キュ'},
		{rom: 'kyo', hira: 'きょ', kata: 'キョ'},
		{rom: 'sha', hira: 'しゃ', kata: 'シャ'},
		{rom: 'shu', hira: 'しゅ', kata: 'シュ'},
		{rom: 'sho', hira: 'しょ', kata: 'ショ'},
		{rom: 'cha', hira: 'ちゃ', kata: 'チャ'},
		{rom: 'chu', hira: 'ちゅ', kata: 'チュ'},
		{rom: 'cho', hira: 'ちょ', kata: 'チョ'},
		{rom: 'nya', hira: 'にゃ', kata: 'ニャ'},
		{rom: 'nyu', hira: 'にゅ', kata: 'ニュ'},
		{rom: 'nyo', hira: 'にょ', kata: 'ニョ'},
		{rom: 'hya', hira: 'ひゃ', kata: 'ヒャ'},
		{rom: 'hyu', hira: 'ひゅ', kata: 'ヒュ'},
		{rom: 'hyo', hira: 'ひょ', kata: 'ヒョ'},
		{rom: 'mya', hira: 'みゃ', kata: 'ミャ'},
		{rom: 'myu', hira: 'みゅ', kata: 'ミュ'},
		{rom: 'myo', hira: 'みょ', kata: 'ミョ'},
		{rom: 'rya', hira: 'りゃ', kata: 'リャ'},
		{rom: 'ryu', hira: 'りゅ', kata: 'リュ'},
		{rom: 'ryo', hira: 'りょ', kata: 'リョ'},
	],
	youonDakutenHandakuten: [
		{rom: 'gya', hira: 'ぎゃ', kata: 'ギャ'},
		{rom: 'gyu', hira: 'ぎゅ', kata: 'ギュ'},
		{rom: 'gyo', hira: 'ぎょ', kata: 'ギョ'},
		{rom: 'ja', hira: 'じゃ', kata: 'ジャ'},
		{rom: 'ju', hira: 'じゅ', kata: 'ジュ'},
		{rom: 'jo', hira: 'じょ', kata: 'ジョ'},
		{rom: 'bya', hira: 'びゃ', kata: 'ビャ'},
		{rom: 'byu', hira: 'びゅ', kata: 'ビュ'},
		{rom: 'byo', hira: 'びょ', kata: 'ビョ'},
		{rom: 'pya', hira: 'ぴゃ', kata: 'ピャ'},
		{rom: 'pyu', hira: 'ぴゅ', kata: 'ピュ'},
		{rom: 'pyo', hira: 'ぴょ', kata: 'ピョ'},
	],
}
